//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renamer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Renamer.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory doesn&apos;t exist..
        /// </summary>
        internal static string mainform_dir_not_exist {
            get {
                return ResourceManager.GetString("mainform_dir_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened when renaming &quot;{0}&quot; to &quot;{1}&quot;:.
        /// </summary>
        internal static string mainform_error_when_renaming_format {
            get {
                return ResourceManager.GetString("mainform_error_when_renaming_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Rename.
        /// </summary>
        internal static string mainform_fail_to_rename {
            get {
                return ResourceManager.GetString("mainform_fail_to_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} doesn&apos;t exist..
        /// </summary>
        internal static string mainform_file_not_exist_format {
            get {
                return ResourceManager.GetString("mainform_file_not_exist_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string mainform_file_not_found {
            get {
                return ResourceManager.GetString("mainform_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path is empty..
        /// </summary>
        internal static string mainform_file_path_empty {
            get {
                return ResourceManager.GetString("mainform_file_path_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of files are not match. (Old: {0}, New: {1}).
        /// </summary>
        internal static string mainform_files_count_no_match_format {
            get {
                return ResourceManager.GetString("mainform_files_count_no_match_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files and folders have been renamed..
        /// </summary>
        internal static string mainform_files_renamed_format {
            get {
                return ResourceManager.GetString("mainform_files_renamed_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is empty..
        /// </summary>
        internal static string mainform_folder_missing {
            get {
                return ResourceManager.GetString("mainform_folder_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following files already exist and cannot be used as new name:.
        /// </summary>
        internal static string mainform_following_files_already_exist {
            get {
                return ResourceManager.GetString("mainform_following_files_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following files don&apos;t exist:.
        /// </summary>
        internal static string mainform_following_files_not_exist {
            get {
                return ResourceManager.GetString("mainform_following_files_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Directory.
        /// </summary>
        internal static string mainform_invalid_dir {
            get {
                return ResourceManager.GetString("mainform_invalid_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing in the list files..
        /// </summary>
        internal static string mainform_list_file_empty {
            get {
                return ResourceManager.GetString("mainform_list_file_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file or directory in {0}.
        /// </summary>
        internal static string mainform_no_file_in_dir_format {
            get {
                return ResourceManager.GetString("mainform_no_file_in_dir_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        internal static string mainform_problem {
            get {
                return ResourceManager.GetString("mainform_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string mainform_success {
            get {
                return ResourceManager.GetString("mainform_success", resourceCulture);
            }
        }
    }
}
